### ISSUE TITLE
How to run your code to reproduce the results?

### ISSUE THREAD

**Issue by Neko9810** [miguelvalente/Invertible-Zero-Shot-Recognition-Flows#1]
Hi, I'm interested of your paper IZF., and I want to reproduce the results in the paper. how do I run this code?

**Comment by miguelvalente** [comment]
Hi,

To reproduce results just change the weights&bias project to your own(you can find [here](https://github.com/miguelvalente/Invertible-Zero-Shot-Recognition-Flows/blob/2c0fec50ae34a24f13c63ec923e6a0b52a38bdc9/train.py#L19) and run train.py either on the console or your editor of choice. Let me know if you need anything else.

To note that this code only works to view the toydata. I have an updated version but is set to private right now
